#!/usr/bin/env bash
# This script configures the servers to the listening port 80 of all the servers active in IPv4 IPs

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
