#!/usr/bin/env bash
# This script configures the server on listening port 20 of all the active servers IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
